import { chromium, pastaDeFotos } from "./_comum.mjs";
const OUT = pastaDeFotos("01-casca");
const browser = await chromium.launch({ channel: "chrome", headless: true });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const page = await ctx.newPage();
page.on("response", r => { if (r.url().includes("/api/") && r.request().method() !== "GET") console.log("API", r.request().method(), r.url(), r.status()); });
await page.goto(`http://localhost:3200/?tela=agenda`, { waitUntil: "networkidle" }); await page.waitForTimeout(1000);
await page.locator('button[aria-label^="Marcar atendimento"]').nth(2).click({ force: true }); await page.waitForTimeout(500);
const sels = page.locator('[role="dialog"] select');
const optC = await sels.nth(0).locator("option").nth(1).getAttribute("value");
await sels.nth(0).selectOption(optC);
const optS = await sels.nth(1).locator("option").nth(1).getAttribute("value");
await sels.nth(1).selectOption(optS);
await page.waitForTimeout(300);
await page.screenshot({ path: `${OUT}/gaveta-novo-preenchido-d.png` });
await page.getByRole("button", { name: /Marcar atendimento/ }).last().click();
await page.waitForTimeout(2500);
await page.screenshot({ path: `${OUT}/apos-marcar-d.png` });
console.log("dialog?", await page.locator('[role="dialog"]').count(), await page.evaluate(() => document.querySelector('[role="dialog"]')?.innerText?.slice(0,300)));
await browser.close();
